### ISSUE TITLE
Could not auto-detect SDL2 sdk configuration

### ISSUE THREAD

**Issue by KeirMeikle** [Jack-Ji/jok#32] opened 2024-10-18 22:39 UTC
Hi I'm getting this error when trying to build. Running on Windows 10. Tried setting `SDL_CONFIG_PATH` in windows environment vars, but it doesn't seem to fix things. Tried setting it to `E:\Github\zigtest\.build_config\sdl.json`, `E:\Github\zigtest\.build_config`, `E:\Github\zigtest` all the same result. My example was set up by following the [ jok readme](https://github.com/Jack-Ji/jok/blob/main/README.md). 

```
Could not auto-detect SDL2 sdk configuration. Please provide C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\.build_config\sdl.json with the following contents filled out:
{
  "x86_64-windows-gnu": {
    "include": "<path to sdk>/include",
    "libs": "<path to sdk>/lib",
    "bin": "<path to sdk>/bin"
  }
}
```

**Comment by Jack-Ji** [comment] 2024-10-19 01:23
That's weird. Could you paste output of `zig env` and content of build.zig/build.zig.zon?
You can also try `echo %SDL_CONFIG_PATH%` in you command terminal, to make sure environment variable has taken effect.

**Comment by Jack-Ji** [comment] 2024-10-19 01:42
Judging from the error log, you are not using latest master, otherwise the reported path to `.build_config\sdl.json` should be prefixed with your project's path instead of zig's package cache. You should try upgrade the `jok` dependency.

**Comment by KeirMeikle** [comment] 2024-10-19 20:56
```
E:\Github\zigtest>zig env
{
 "zig_exe": "C:\\Tools\\zig\\0.14.0-dev.1951+857383689\\files\\zig.exe",
 "lib_dir": "C:\\Tools\\zig\\0.14.0-dev.1951+857383689\\files\\lib",
 "std_dir": "C:\\Tools\\zig\\0.14.0-dev.1951+857383689\\files\\lib\\std",
 "global_cache_dir": "C:\\Users\\User\\AppData\\Local\\zig",
 "version": "0.14.0-dev.1951+857383689",
 "target": "x86_64-windows.win10_cu...win10_cu-gnu",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "ZIG_DEBUG_CMD": null,
  "CC": null,
  "NO_COLOR": null,
  "CLICOLOR_FORCE": null,
  "XDG_CACHE_HOME": null,
  "HOME": null
 }
}
E:\Github\zigtest>echo %SDL_CONFIG_PATH% 
E:\Github\zigtest\.build_config\sdl.json
E:\Github\zigtest>zig build             
Could not auto-detect SDL2 sdk configuration. Please provide C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\.build_config\sdl.json with the following contents filled out:
{
  "x86_64-windows-gnu": {
    "include": "<path to sdk>/include",
    "libs": "<path to sdk>/lib",
    "bin": "<path to sdk>/bin"
  }
}
```

**Comment by KeirMeikle** [comment] 2024-10-19 20:58
I've run the fetch step like so:

`zig fetch --save git+https://github.com/jack-ji/jok.git`

Is there anything else I need to do to update the jok dependency?

**Comment by KeirMeikle** [comment] 2024-10-19 21:00
For reference:

```
E:\Github\zigtest>zig fetch --save git+https://github.com/jack-ji/jok.git             
info: resolved to commit 81b14e80d4d03f2310ab97132f0d1c8633ed847d
info: existing dependency named 'jok' is up-to-date
```

**Comment by Jack-Ji** [comment] 2024-10-20 00:49
I think you're good to go. Please paste error log and content of `build.zig.zon` if problem isn't fixed still.

**Comment by KeirMeikle** [comment] 2024-10-20 20:11
No change for me. Posted the full error and zon file below.

Error log

```
PS E:\Github\zigtest> zig build run
Could not auto-detect SDL2 sdk configuration. Please provide C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\.build_config\sdl.json with the following contents filled out:
{
  "x86_64-windows-gnu": {
    "include": "<path to sdk>/include",
    "libs": "<path to sdk>/lib",
    "bin": "<path to sdk>/bin"
  }
}

You can obtain a SDL2 sdk for Windows from https://github.com/libsdl-org/SDL/releases
thread 7560 panic: Failed to get paths for SDL2: FileNotFound
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:364:28: 0x7e0760 in link__anon_65850 (build.exe.obj)
            std.debug.panic("Failed to get paths for {s}: {s}", .{ @tagName(library), @errorName(err) });
                           ^
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:48:17: 0x95230e in build (build.exe.obj)
        sdk.link(lib_test, .dynamic, .SDL2);
                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2295:44: 0x8f33d2 in runBuild__anon_123135 (build.exe.obj)
        .error_union => try build_zig.build(b),
                                           ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2275:29: 0x897f66 in dependencyInner__anon_80106 (build.exe.obj)
        sub_builder.runBuild(bz) catch @panic("unhandled error");
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2097:35: 0x80b6a3 in dependency__anon_75130 (build.exe.obj)
            return dependencyInner(b, name, pkg.build_root, if (@hasDecl(pkg, "build_zig")) pkg.build_zig else null, pkg_hash, pkg.deps, args);
                                  ^
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:148:21: 0x80bf07 in init (build.exe.obj)
        b.dependency(name, .{}).builder
                    ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:415:20: 0x7df3e5 in getSdlSdk (build.exe.obj)
    return sdl.init(builder, .{ .maybe_config_path = sdl_config_path });
                   ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:98:30: 0x7a562e in createDesktopApp (build.exe.obj)
    const sdl_sdk = getSdlSdk(b, opt);
                             ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:55:37: 0x94d093 in build (build.exe.obj)
        const exe = createDesktopApp(
                                    ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2294:33: 0x8f3125 in runBuild__anon_123131 (build.exe.obj)
        .void => build_zig.build(b),
                                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2275:29: 0x8973d6 in dependencyInner__anon_80035 (build.exe.obj)
        sub_builder.runBuild(bz) catch @panic("unhandled error");
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2097:35: 0x80b553 in dependency__anon_75130 (build.exe.obj)
            return dependencyInner(b, name, pkg.build_root, if (@hasDecl(pkg, "build_zig")) pkg.build_zig else null, pkg_hash, pkg.deps, args);
                                  ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:421:21: 0x7df253 in getJokBuilder (build.exe.obj)
        b.dependency(dep, .{}).builder
                    ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:97:34: 0x7a5619 in createDesktopApp (build.exe.obj)
    const builder = getJokBuilder(b, opt);
                                 ^
E:\Github\zigtest\build.zig:7:37: 0x76213e in build (build.exe.obj)
    const exe = jok.createDesktopApp(
                                    ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2294:33: 0x74b465 in runBuild__anon_4660 (build.exe.obj)
        .void => build_zig.build(b),
                                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\compiler\build_runner.zig:335:29: 0x74653e in main (build.exe.obj)
        try builder.runBuild(root);
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\start.zig:439:53: 0x74dbd7 in WinStartup (build.exe.obj)
    std.os.windows.ntdll.RtlExitUserProcess(callMain());
                                                    ^
???:?:?: 0x7ffe84517373 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe8465cc90 in ??? (ntdll.dll)
error: unable to read results of configure phase from 'E:\Github\zigtest\.zig-cache\tmp\e9286207d70a5e95': FileNotFound
PS E:\Github\zigtest> zig build run
Could not auto-detect SDL2 sdk configuration. Please provide C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\.build_config\sdl.json with the following contents filled out:
{
  "x86_64-windows-gnu": {
    "include": "<path to sdk>/include",
    "libs": "<path to sdk>/lib",
    "bin": "<path to sdk>/bin"
  }
}

You can obtain a SDL2 sdk for Windows from https://github.com/libsdl-org/SDL/releases
thread 2636 panic: Failed to get paths for SDL2: FileNotFound
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:364:28: 0xc60760 in link__anon_65850 (build.exe.obj)
            std.debug.panic("Failed to get paths for {s}: {s}", .{ @tagName(library), @errorName(err) });
                           ^
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:48:17: 0xdd230e in build (build.exe.obj)
        sdk.link(lib_test, .dynamic, .SDL2);
                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2295:44: 0xd733d2 in runBuild__anon_123135 (build.exe.obj)
        .error_union => try build_zig.build(b),
                                           ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2275:29: 0xd17f66 in dependencyInner__anon_80106 (build.exe.obj)
        sub_builder.runBuild(bz) catch @panic("unhandled error");
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2097:35: 0xc8b6a3 in dependency__anon_75130 (build.exe.obj)
            return dependencyInner(b, name, pkg.build_root, if (@hasDecl(pkg, "build_zig")) pkg.build_zig else null, pkg_hash, pkg.deps, args);
                                  ^
C:\Users\User\AppData\Local\zig\p\1220dc7b8b63eab7a4184fde897e51f8f1301d8615a0bbb0c9f8f0b693fa38055c4e\build.zig:148:21: 0xc8bf07 in init (build.exe.obj)
        b.dependency(name, .{}).builder
                    ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:415:20: 0xc5f3e5 in getSdlSdk (build.exe.obj)
    return sdl.init(builder, .{ .maybe_config_path = sdl_config_path });
                   ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:98:30: 0xc2562e in createDesktopApp (build.exe.obj)
    const sdl_sdk = getSdlSdk(b, opt);
                             ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:55:37: 0xdcd093 in build (build.exe.obj)
        const exe = createDesktopApp(
                                    ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2294:33: 0xd73125 in runBuild__anon_123131 (build.exe.obj)
        .void => build_zig.build(b),
                                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2275:29: 0xd173d6 in dependencyInner__anon_80035 (build.exe.obj)
        sub_builder.runBuild(bz) catch @panic("unhandled error");
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2097:35: 0xc8b553 in dependency__anon_75130 (build.exe.obj)
            return dependencyInner(b, name, pkg.build_root, if (@hasDecl(pkg, "build_zig")) pkg.build_zig else null, pkg_hash, pkg.deps, args);
                                  ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:421:21: 0xc5f253 in getJokBuilder (build.exe.obj)
        b.dependency(dep, .{}).builder
                    ^
C:\Users\User\AppData\Local\zig\p\122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f\build.zig:97:34: 0xc25619 in createDesktopApp (build.exe.obj)
    const builder = getJokBuilder(b, opt);
                                 ^
E:\Github\zigtest\build.zig:7:37: 0xbe213e in build (build.exe.obj)
    const exe = jok.createDesktopApp(
                                    ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\Build.zig:2294:33: 0xbcb465 in runBuild__anon_4660 (build.exe.obj)
        .void => build_zig.build(b),
                                ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\compiler\build_runner.zig:335:29: 0xbc653e in main (build.exe.obj)
        try builder.runBuild(root);
                            ^
C:\Tools\zig\0.14.0-dev.1951+857383689\files\lib\std\start.zig:439:53: 0xbcdbd7 in WinStartup (build.exe.obj)
    std.os.windows.ntdll.RtlExitUserProcess(callMain());
                                                    ^
???:?:?: 0x7ffe84517373 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe8465cc90 in ??? (ntdll.dll)
error: unable to read results of configure phase from 'E:\Github\zigtest\.zig-cache\tmp\b3690d2b08977020': FileNotFound
```

build.zig.zon

```
.{
    .name = "zigtest",
    .version = "0.0.0",
    .dependencies = .{
        .jok = .{
            .url = "git+https://github.com/jack-ji/jok.git#81b14e80d4d03f2310ab97132f0d1c8633ed847d",
            .hash = "122087c8e1acb070d3c2dcce86446749441e35d78fce69323502a4e52e8625473a6f",
        },
    },
    .paths = .{
        "build.zig",
        "build.zig.zon",
        "src",
    },
}
```

**Comment by Jack-Ji** [comment] 2024-10-20 23:08
ok, I'll try it in virtualbox later.

**Comment by Jack-Ji** [comment] 2024-10-21 14:39
The problem is caused by latest change of zig's building system (happens now and then), I might need some time to properly fix it.

**Comment by Jack-Ji** [comment] 2024-10-23 14:39
I think it's fixed now. Please update dependency again and retry.

**Comment by Jack-Ji** [comment] 2024-10-24 12:41
It works fine in virtualbox now, closing the issue.
Feel free to file issue if anything goes wrong again.

**Closed by Jack-Ji** 2024-10-24 12:41 UTC
Labels: bug
